#!/usr/bin/env python3
"""Rebuild the dated priority comparison without rerunning a large certificate.

The admitted prior closure omits this work's three-colour claims. A separate
published statement remains a comparator even though its proof is unresolved.
All operations here are exact integer arithmetic on small input registries.
"""
import argparse
import hashlib
import json
from pathlib import Path
import close_baselines as cb

ROOT = Path(__file__).resolve().parents[1]


def require(condition, message):
    if not condition:
        raise ValueError(message)


def build():
    claims = json.loads(cb.CLAIMS_PATH.read_text())["claims"]
    for c in claims:
        p = c["prime"]
        require(cb.least_prime_factor(p) == p, (c["id"], "not prime"))
        require((p-1) % c["colors"] == 0 and p > c["length"], (c["id"], "preconditions"))
        require(c["lower_bound"] == (c["length"]-1)*p+1, (c["id"], "strict bound"))
    _, nodes, winners, direct = cb.closure()
    _, old_nodes, old_winners, _ = cb.closure(include_current_three_color=False)
    path = ROOT / "audit/published-unresolved.json"
    ledger = json.loads(path.read_text())
    for s in ledger["statements"][0]["specializations"]:
        p, q = s["prime_p"], s["prime_q"]
        require(p >= 5 and cb.least_prime_factor(p) == p, "LR parameter p")
        require(cb.least_prime_factor(q) == q, "LR parameter q")
        require(s["length"] == p+1 and s["lower_bound"] == p*(q**p-1), "LR specialization")
    rows = []
    for k in range(17, 29):
        parent = old_nodes[old_winners[("ordinary", 3, k)]]
        lr_p = max(p for p in cb.primes_up_to(k-1) if p >= 5)
        lr = lr_p*(3**lr_p-1)
        prior = max(parent["lower_bound"], lr)
        d = direct.get((3, k), {}).get("lower_bound")
        rows.append({"length":k,"direct_bound":d,
                     "admitted_prior_bound":parent["lower_bound"],
                     "admitted_prior_node":parent,
                     "published_unresolved_bound":lr,"published_unresolved_prime":lr_p,
                     "prior_comparator":prior,
                     "comparator_status":"published_unresolved" if lr>parent["lower_bound"] else "admitted",
                     "improved":d is not None and d>prior,
                     "winning_admitted_bound":nodes[winners[("ordinary",3,k)]]["lower_bound"]})
    require([r["length"] for r in rows if r["improved"]] == list(range(17,22)), "The five stated improvements are not recovered")
    # Retain the complete ancestry of the reported three-colour comparators.
    # Unrelated four-colour consequences are outside this comparison artifact.
    needed = {r["admitted_prior_node"]["id"] for r in rows}
    pending = list(needed)
    while pending:
        for parent in old_nodes[pending.pop()]["parents"]:
            if parent not in needed:
                needed.add(parent)
                pending.append(parent)
    result={"schema":"vdw-publication-comparison/v1", "review_date":ledger["review_date"],
            "scope":"Finite registered constructions plus the published Landman-Robertson comparator; no claim of exhaustive global priority.",
            "inputs_sha256":{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest()
                             for p in (cb.CLAIMS_PATH, cb.BASELINES_PATH, path)},
            "primitive_three_colour_certificates":3,"improved_lengths":[17,18,19,20,21],
            "large_certificate_executions_performed":0,"rows":rows,
            "admitted_prior_provenance_nodes":[old_nodes[key] for key in sorted(needed)]}
    ti=cb.tex_int
    table=[r"% Generated by tools/publication_comparison.py; do not edit.",r"\begin{table}[htbp]",
           r"\centering\small",r"\begin{tabular}{@{}c r r l@{}}",r"\toprule",
           r"$k$ & new strict bound & prior comparator & comparator source \\",r"\midrule"]
    for r in rows[:5]:
        k=r["length"];source="Monroe tally" if k<20 else (r"Landman--Robertson$^{*}$" if k==20 else "BCT from two colours")
        table.append(f'{k} & ${ti(r["direct_bound"])}$ & ${ti(r["prior_comparator"])}$ & {source} '+r"\\")
    table += [r"\bottomrule",r"\end{tabular}",r"\caption{The five improvements over prior comparators identified through",
              r"26 September 2026. Every numerical entry $B$ uses the strict convention",
              r"$W(3,k)>B$. $^{*}$The published Landman--Robertson statement is included",
              r"for a conservative comparison; its proof was not verified in our review.",
              r"The finite prior closure excludes the new three-colour claims.}",
              r"\label{tab:priority}",r"\end{table}"]
    unresolved=[r"% Generated by tools/publication_comparison.py; do not edit.",r"\begin{table}[htbp]",r"\centering\small",
                r"\begin{tabular}{@{}c r r@{}}",r"\toprule",r"$k$ & best admitted consequence & published unresolved statement \\",r"\midrule"]
    for r in rows:
        if r["length"]==20 or r["length"]>=24:
            unresolved.append(f'{r["length"]} & ${ti(r["winning_admitted_bound"])}$ & ${ti(r["published_unresolved_bound"])}$ '+r"\\")
    unresolved += [r"\bottomrule",r"\end{tabular}",r"\caption{Two distinct comparison levels. The middle column uses the checked",
                   r"seed registry, including this work. The last column records the numerical",
                   r"consequences of the stronger published Landman--Robertson statement and",
                   r"length monotonicity; these are not certified by this paper.}",r"\label{tab:unresolved}",r"\end{table}"]
    return {
        ROOT/"audit/generated/publication_comparison.json":json.dumps(result,indent=2)+"\n",
        ROOT/"paper/tex/generated_priority_comparison.tex":"\n".join(table)+"\n",
        ROOT/"paper/tex/generated_unresolved_comparison.tex":"\n".join(unresolved)+"\n",
    }


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args()
    for path,content in build().items():
        if args.check:
            if path.read_text()!=content:raise SystemExit(f"Stale comparison: {path}")
        else:path.write_text(content)
    print("PUBLICATION_COMPARISON_OK: five improvements; no large certificate rerun")


if __name__=="__main__":main()
