#!/usr/bin/env python3
"""Validate and render the campaign scanner-revision registry."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "audit" / "scanner_revisions.json"
OUT_TEX = ROOT / "paper" / "tex" / "generated_scanner_revisions.tex"
OUT_MD = ROOT / "audit" / "generated" / "scanner_revisions.md"


def load_registry(path: Path = INPUT) -> dict:
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    window = data["campaign_window"]
    expected = 1
    total = 0
    seen_revisions: set[str] = set()
    seen_fingerprints: set[str] = set()
    for item in data["fingerprints"]:
        if item["source_sha256_prefix"] in seen_fingerprints:
            raise ValueError("duplicate source fingerprint")
        seen_fingerprints.add(item["source_sha256_prefix"])
        if item["first_chunk"] != expected:
            raise ValueError(f"chunk gap before {item['first_chunk']}")
        count = item["last_chunk"] - item["first_chunk"] + 1
        revision_count = sum(entry["chunks"] for entry in item["revisions"])
        if revision_count != count:
            raise ValueError(
                f"{item['source_sha256_prefix']}: {revision_count} revision chunks != {count}"
            )
        for entry in item["revisions"]:
            if not re.fullmatch(r"[0-9a-f]{40}", entry["git"]):
                raise ValueError(f"revision is not a full Git SHA: {entry['git']}")
            if entry["git"] in seen_revisions:
                raise ValueError(f"duplicate revision {entry['git']}")
            seen_revisions.add(entry["git"])
        targets = item.get("active_targets")
        if (
            not isinstance(targets, list)
            or len(targets) != item["target_count"]
            or len(targets) != len(set(targets))
            or any(not re.fullmatch(r"[2-9],[0-9]+", target) for target in targets)
        ):
            raise ValueError(f"invalid active target registry for {item['source_sha256_prefix']}")
        total += count
        expected = item["last_chunk"] + 1
    if total != window["chunk_count"] or expected != window["chunk_count"] + 1:
        raise ValueError("registry does not cover all campaign chunks")
    if len(seen_revisions) != 8 or len(seen_fingerprints) != 4:
        raise ValueError("expected eight revisions and four source fingerprints")
    enumerator = data.get("prime_enumerator", {})
    if (
        enumerator.get("function_bytes") != 249
        or not re.fullmatch(r"[0-9a-f]{64}", str(enumerator.get("function_sha256", "")))
        or enumerator.get("identical_in_all_four_github_blobs") is not True
    ):
        raise ValueError("prime enumerator identity evidence is incomplete")
    lo = window["lower_inclusive"]
    width = window["chunk_width"]
    for index in range(1, window["chunk_count"] + 1):
        upper = min(lo + index * width, window["upper_exclusive"])
        if upper <= 2 or upper % 2:
            raise ValueError("campaign boundary invariant does not imply composite endpoints")
    return data


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def render_tex(data: dict) -> str:
    lines = [
        "% Generated by tools/render_scanner_revisions.py; do not edit by hand.",
        r"\begin{table}[ht]",
        r"\centering\scriptsize",
        r"\begin{tabular}{l l P{3.0cm} c P{5.0cm}}",
        r"\toprule",
        r"source hash & chunks & revisions (number of chunks) & targets & change and transition check \\",
        r"\midrule",
    ]
    for item in data["fingerprints"]:
        revisions = ", ".join(
            rf"\texttt{{{entry['git'][:7]}}} ({entry['chunks']})"
            for entry in item["revisions"]
        )
        detail = tex_escape(f"{item['change']} {item['cross_test']}")
        lines.append(
            rf"\texttt{{{item['source_sha256_prefix']}}} & "
            rf"{item['first_chunk']}--{item['last_chunk']} & {revisions} & "
            rf"{item['target_count']} & {detail} \\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Scanner-source fingerprints and Git revisions used by the 515 campaign chunks.  The registry also records the active target list and Git blob identity.}",
        r"\label{tab:scanner-revisions}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def render_md(data: dict) -> str:
    lines = [
        "# Scanner revision registry",
        "",
        "| source SHA-256 prefix | chunks | revisions (counts) | targets | change | cross-test |",
        "|---|---:|---|---:|---|---|",
    ]
    for item in data["fingerprints"]:
        revisions = ", ".join(
            f"`{entry['git']}` ({entry['chunks']})" for entry in item["revisions"]
        )
        lines.append(
            f"| `{item['source_sha256_prefix']}` | {item['first_chunk']}--{item['last_chunk']} "
            f"| {revisions} | {item['target_count']} | {item['change']} | {item['cross_test']} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated file is stale: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = load_registry()
    write_or_check(OUT_TEX, render_tex(data), args.check)
    write_or_check(OUT_MD, render_md(data), args.check)


if __name__ == "__main__":
    main()
